/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1121932_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1121932_1[] = { "idle", "pick_up", "put_down", "random" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1121932_4_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_1121932_4_axes_size = 6;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1121932_4 = {
    4, // uint32_t blockId
    4, // int implementationVersion
    6, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1121932_4[78] = { 1.3803955097802174, 0.306235996230195, -0.083513481518588, 2.3068257035353246, 3.588481841274561, 0.5694054719538261, 0.18640883615574774, -0.2762232094358366, -0.6172444005019199, -0.8712953321146182, -0.9145215585326346, -1.043310352577231, -1.1231709690048144, 3.3343332240310235, 0.0014657263094798112, -0.4203208416628723, 2.126683927499331, 2.900263943255712, 1.0325850136578083, 0.5643526797111218, 0.049518769714408196, -0.4652976615426059, -0.4651728694040615, -0.41435864161198527, -0.6224928983152868, -0.8671701349652349, 0.9282090805518703, 0.20740100661388192, 0.17926416117459154, 2.236410155510291, 3.3496642219475827, 0.36546208117252743, 0.08488573967210519, -0.48885303837223315, -0.8820461325156383, -1.166576056018806, -1.2144752946228554, -1.3415061172862084, -1.37135751461849, 19.271350645101986, -0.06247089612178314, 0.36575780968325067, 2.3385000267089944, 3.680400965287565, 2.88600148105373, 2.360661537792438, 2.0513963401317596, 1.7020663751337008, 1.4091559279805574, 1.3308390883299022, 1.2405967273009129, 1.2050674901558802, 24.199026280488724, -0.26263650729416466, 1.725566809829802, 2.192481885353724, 3.179931911233908, 3.4929333279530206, 2.9166394005983305, 2.338251003088095, 2.0326257954614286, 1.8775360776254764, 1.813790772157984, 1.7245012166557643, 1.6808514318739374, 37.18922179517074, 0.08230844169902878, -0.013666633355359618, 2.4162475925225477, 3.9308223388133903, 3.120780276761462, 2.530469559180813, 2.119432171675353, 1.8705949934486013, 1.704672485589981, 1.6524630039930344, 1.5528078705836565, 1.5164981251343703 };
const float ei_dn_standard_scaler_scale_1121932_4[78] = { 0.9801754859231064, 1.809448248559564, 0.9159248622563773, 2.865539166769516, 0.9024744600241926, 1.26320066333041, 1.289773200313456, 1.3128459987868164, 1.210879246980714, 1.1893260131751624, 1.1231527324901371, 1.1798526047381015, 1.2776853097571128, 0.39996981381100716, 1.5786860330111667, 0.7053817467133912, 2.103474576762953, 0.5882730661408866, 1.0477373814578437, 1.047691789802463, 1.0231695169588282, 1.062101416982482, 0.9217741202600727, 0.8453257551743459, 0.913608884396346, 1.096105772182077, 1.643536120072382, 1.7102351374302225, 0.6738092218037822, 2.4589658404888697, 0.7531184945338478, 1.2780908291512039, 1.2186240900718979, 1.3003944722053624, 1.284539198693591, 1.1690464946287935, 1.1303195302746756, 1.1482157312431183, 1.2836747689191852, 0.0801959885057873, 1.0243207245095276, 0.8033719461681744, 3.206683006332719, 0.964546102034351, 1.1174130237097633, 1.11354550403766, 1.0065412556203832, 0.9786282084492254, 1.0398845192254496, 1.0217617176178246, 1.0482361878560122, 1.0519489085292146, 0.06343790557528092, 1.0956088806963584, 0.3597510464774898, 2.555399191888296, 0.7482352823663332, 1.1203967034335425, 1.1287125721450242, 1.067728290501746, 1.080846390334522, 1.051710983829477, 1.024821654115478, 1.0430927680346285, 1.0585487794810253, 0.05417225607498381, 1.0642669594408265, 0.8387241634639379, 6.392794886934396, 1.859267439284325, 0.9784473702315364, 1.0033951100256093, 0.9213535950709769, 0.9262806176084948, 0.8928494067286928, 0.8691557435452166, 0.8865674596889889, 0.8987799602000707 };
const float ei_dn_standard_scaler_var_1121932_4[78] = { 1.040860018362501, 0.30542716919095936, 1.1920111129612576, 0.1217831777919967, 1.2278071539499575, 0.6266936726149606, 0.6011367827499089, 0.5801929271517238, 0.6820219122563198, 0.7069654078362563, 0.7927246518671124, 0.7183638819980205, 0.612565025403138, 6.250943425198725, 0.4012439218293384, 2.0097940940248744, 0.22600886029543396, 2.8896288878450562, 0.9109512201296627, 0.9110305042820351, 0.9552230954925839, 0.8864781254509015, 1.1769309360737925, 1.3994319911187447, 1.198062215382553, 0.8323290840337461, 0.37020432989164653, 0.34189153660137384, 2.2025516378943992, 0.16538457772672596, 1.7630855026224934, 0.6121763713508012, 0.6733804162569728, 0.5913570389349884, 0.6060455640169161, 0.7317056895077948, 0.7827039701443436, 0.7584955106833999, 0.6068620640139669, 155.4872240794916, 0.9530772010005415, 1.5494111462480642, 0.09724962592184792, 1.0748652423485903, 0.8008893937224829, 0.8064622858056035, 0.9870447423676334, 1.044153960638351, 0.924761571197476, 0.9578571516302332, 0.9100844685497186, 0.9036717488598347, 248.48623034703263, 0.8330842276389151, 7.72673233890156, 0.153137831770536, 1.7861734669669507, 0.7966294461142438, 0.7849342418538118, 0.8771593562153748, 0.8559966144552493, 0.9040806637666926, 0.9521457064268244, 0.9190817262311141, 0.8924383991738754, 340.75807371651877, 0.8828742309235923, 1.4215485272446688, 0.024469126118605956, 0.28927857708748794, 1.0445399607365882, 0.9932442043880377, 1.1780055333947947, 1.165506894473998, 1.25442173768946, 1.323746397385528, 1.2722616194099952, 1.2379218796161218 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1121932_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1121932_4,
    .mean_data_len = 78,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1121932_4,
    .scale_data_len = 78,
    .var_data = (float *)ei_dn_standard_scaler_var_1121932_4,
    .var_data_len = 78
};
ei_data_normalization_t ei_data_normalization_config_1121932_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_1121932_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1121932_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1121932_1[ei_dsp_blocks_1121932_1_size] = {
    { // DSP block 4
        4,
        78, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1121932_4, // pointer to config struct
        ei_dsp_config_1121932_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1121932_4_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1121932_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1121932_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1121932_3_init,
    .model_invoke = &tflite_learn_1121932_3_invoke,
    .model_reset = &tflite_learn_1121932_3_reset,
    .model_input = &tflite_learn_1121932_3_input,
    .model_output = &tflite_learn_1121932_3_output,
};

const uint8_t ei_output_tensors_indices_1121932_3[1] = { 0 };
const uint8_t ei_output_tensors_size_1121932_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1121932_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_1121932_3,
    .output_tensors_size = ei_output_tensors_size_1121932_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1121932_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1121932_1_size = 1;
const uint32_t ei_learning_block_1121932_3_inputs[1] = { 4 };
const uint8_t ei_learning_block_1121932_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1121932_1[ei_learning_blocks_1121932_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1121932_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1121932_3_inputs,
        ei_learning_block_1121932_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1121932_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1121932_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1121932_1[ei_postprocessing_blocks_1121932_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1121932_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_1121932_1_size = 0;

uint32_t *freeform_outputs_1121932_1 = nullptr;

const ei_impulse_t impulse_1121932_1 = {
    .project_id = 1121932,
    .project_owner = "poke535",
    .project_name = "poke535-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 2,

    .nn_input_frame_size = 78,
    .raw_sample_count = 300,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 300 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 10,
    .frequency = 100,

    .dsp_blocks_size = ei_dsp_blocks_1121932_1_size,
    .dsp_blocks = ei_dsp_blocks_1121932_1,

    .learning_blocks_size = ei_learning_blocks_1121932_1_size,
    .learning_blocks = ei_learning_blocks_1121932_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1121932_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1121932_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "accX + accY + accZ + gyrX + gyrY + gyrZ",
    .slice_size = (300/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_1121932_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1121932_1_size,
    .freeform_outputs = freeform_outputs_1121932_1
};

ei_impulse_handle_t impulse_handle_1121932_1 = ei_impulse_handle_t( &impulse_1121932_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1121932_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1121932_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1121932_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1121932_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
